### ISSUE TITLE
Namespaced 'Page' class causes error Class 'Page' not found in 'ErrorPage.php'

### ISSUE THREAD

**Issue by obj63mc** [silverstripe/silverstripe-errorpage#7] opened 2017-08-16 17:06 UTC
I am trying to get started with v4 beta but if you namespace your page class this module throws an error.  Can you tell me a way to work around this or do I have to not namespace 'mysite' code... or fork this and update namespace and use that for composer.

Example - Directory mysite/src/Pages/Page.php - 

    namespace Moosylvania\Mysite\Pages; 
    class Page...

**Comment by dhensby** [comment] 2017-08-16 19:38
duplicate of https://github.com/silverstripe/silverstripe-cms/issues/1911

If you namespace you Page class then there is no Page class in the global namespace which is required for the assumptions this (and many other modules) will be making.

**Closed by dhensby** 2017-08-16 19:38 UTC
